### ISSUE TITLE
After installing grua

### ISSUE THREAD

**Issue by digcat** [marsbard/grua#1]
Im seeing a file exists error when using grua

http://pastebin.com/gut3kiss

shows installing then running grua

installing grua inself seemed to go ok, and import grua works, but its checking for ~/.grua which exists so to it bombs.

**Comment by digcat** [comment]
$ grua stack
Traceback (most recent call last):
  File "/usr/local/bin/grua", line 26, in <module>
    os.makedirs(grua.ConfigPath + "/" + grua.Project)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/admin/.grua/grua'
$ uname -a
Linux vultr.guest 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by digcat** [comment]
ok this sympton of docker version, grua needs at least
Docker version 1.9.1

**Comment by digcat** [comment]
docker version needed but error persists, have reverted to older version which is working

**Comment by marsbard** [comment]
Sorry about that, try pulling latest
