### ISSUE TITLE
tips for installing Grua on ubuntu server with virtualBox

### ISSUE THREAD

**Issue by mathieuga** [marsbard/grua#3]
Hi,
Thinks for your this work.

I'd like to test installing alfresco with "docker-alfresco".
But with my ubuntu server in virtualBox, i have the following issue with my grua installation.

Have you some tips for help me ?
Thinks
Mathieu

_Device "docker0" does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/grua", line 3, in <module>
    from grua import grua
  File "/usr/local/lib/python2.7/dist-packages/grua-0.1-py2.7.egg/grua/grua.py", line 70, in <module>
    mem.BridgeIp = find_bridge_ip()
  File "/usr/local/lib/python2.7/dist-packages/grua-0.1-py2.7.egg/grua/grua.py", line 29, in find_bridge_ip
    output = subprocess.check_output(('grep', 'inet'), stdin=sp.stdout).strip().split()[1].split('/')[0]
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('grep', 'inet')' returned non-zero exit status 1_

**Comment by marsbard** [comment]
Hi, can you try to pull grua again and reinstall now? I just integrated my refactoring branch and as part of that there was a slightly different way to detect the docker bridge IP address. Can you try it with the latest grua please?

**Comment by mathieuga** [comment]
Think for help.
I reinstall grua with the new version but this update not solve my issue.

For information , i use Ubuntu Server 16.04 LTS

**Comment by marsbard** [comment]
did you get the same error? can you paste again anyway? at least the line numbers will have changed

**Comment by mathieuga** [comment]
Yes i have the same error:
$ grua
Device "docker0" does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/grua", line 3, in <module> from grua import grua
  File "build/bdist.linux-x86_64/egg/grua/grua.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/grua/util.py", line 41, in find_bridge_ip
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('grep', 'inet')' returned non-zero exit status 1

For information my ifconfig
$ ifconfig
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:16:e4:fb
          inet adr:192.168.0.10  Bcast:192.168.0.255  Masque:255.255.255.0
          adr inet6: fe80::a00:27ff:fe16:e4fb/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:303513 erreurs:0 :0 overruns:0 frame:0
          TX packets:237681 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000
          Octets reçus:215430288 (215.4 MB) Octets transmis:24178056 (24.1 MB)

**Comment by marsbard** [comment]
At that point it is trying to run "ip addr show dev docker0" to get the docker bridge IP address... Can you try running that manually?

**Comment by marsbard** [comment]
OK I missed your ifconfig output. Looks like you don't have the docker0 interface. Is the docker daemon running?

**Comment by mathieuga** [comment]
Yes is better with docker daemon running.
Thanks for help !

**Comment by marsbard** [comment]
Funnily enough I am right now working on a branch to make that 'bridge ip' lookup optional as probably very few will need it
